// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBmYZ7M8qKqfiEG9kZXirvIZPL0OdO3ew',
    appId: '1:196738220536:web:7dd0c4ce4e5d38bf5d560d',
    messagingSenderId: '196738220536',
    projectId: 'flutter-7ecb9',
    authDomain: 'flutter-7ecb9.firebaseapp.com',
    storageBucket: 'flutter-7ecb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hnOzuBCloRDk3kOgrtB552dNMopfA-E',
    appId: '1:196738220536:android:5cc14c95799fa6645d560d',
    messagingSenderId: '196738220536',
    projectId: 'flutter-7ecb9',
    storageBucket: 'flutter-7ecb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo0WfKqympVWPZq5oZ63-riAvMm47l7wI',
    appId: '1:196738220536:ios:770ad51b233241cd5d560d',
    messagingSenderId: '196738220536',
    projectId: 'flutter-7ecb9',
    storageBucket: 'flutter-7ecb9.appspot.com',
    iosClientId: '196738220536-1hvjqg5peacc7n0ch7jiv4hm2f0s8rs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo0WfKqympVWPZq5oZ63-riAvMm47l7wI',
    appId: '1:196738220536:ios:a70c91e04f7327305d560d',
    messagingSenderId: '196738220536',
    projectId: 'flutter-7ecb9',
    storageBucket: 'flutter-7ecb9.appspot.com',
    iosClientId: '196738220536-2c6l4oui2o6nudclmqk2atain5sro8e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
